### ISSUE TITLE
Not working with new `drift` package

### ISSUE THREAD

**Issue by kansson** [vanlooverenkoen/moor_db_viewer#48]
`moor` has been renamed to `drift` and the following error now occurs
```dart
class MoorViewerPage extends StatelessWidget {
  final _database = locator<Database>();

  @override
  Widget build(BuildContext context) {
    return MoorDbViewer(_database); // The argument type 'Database' can't be assigned to the parameter type 'GeneratedDatabase'.
  }
}
```

**Comment by vanlooverenkoen** [comment]
Because we need to update the current package. I was thinking of changing the full structure of this library. Make it more dynamic so that everybody can use it with any database. Moor, drift, hive, sqflit,... Because of the name change, I think this is the right moment to change this. I will think about it today and start the implementation.

**Comment by kansson** [comment]
> Because we need to update the current package. I was thinking of changing the full structure of this library. Make it more dynamic so that everybody can use it with any database. Moor, drift, hive, sqflit,... Because of the name change, I think this is the right moment to change this. I will think about it today and start the implementation.

Yes that is a good idea 👍

**Comment by kansson** [comment]
@vanlooverenkoen just got an idea for the potential rewrite. How about spinning up a dart web server so that the database interaction can be done in the browser instead of in the app?

**Comment by vanlooverenkoen** [comment]
Because that is something a colleague of mine already built :D But instead of a webview he created an android studio plugin.
Maybe in the future it would be a nice addition. You can create a new issue for that. But I will start with the rewrite to a more dynamic system.

(For now it is not yet migrated to drift)

https://pub.dev/packages/moor_inspector

**Comment by kansson** [comment]
That is cool didn't know about the package.

**Comment by vanlooverenkoen** [comment]
We use both plugins. moor_inspector during development. moor_db_viewer during testing when not connected to a debugger

**Comment by vanlooverenkoen** [comment]
@essarn I already created a pull request that contains the full refactor. I will do some extra testing.

**Comment by kansson** [comment]
Good job can try it locally tonight if I have time.

**Comment by rajagopalx** [comment]
Thank you for your efforts. Much helpful for moor/drift DB.

Is there any update when this PR gets merged?

**Comment by vanlooverenkoen** [comment]
I have not yet find the time to fully test this. Did you already use my git branch for testing with drift?

**Comment by vanlooverenkoen** [comment]
Everything is available in pub.dev

db_viewer -> https://pub.dev/packages/db_viewer
drift_db_viewer -> https://pub.dev/packages/drift_db_viewer
moor_db_viewer -> https://pub.dev/packages/moor_db_viewer
